([
        ndarray[i,j,k],ndarray[i,j,k+1],ndarray[i,j,k+2],
        ndarray[i,j+1,k],ndarray[i,j+1,k+1],ndarray[i,j+1,k+2],
        ndarray[i,j+2,k],ndarray[i,j+2,k+1],ndarray[i,j+2,k+2],
        ndarray[i+1,j,k],ndarray[i+1,j,k+1],ndarray[i+1,j,k+2],
        ndarray[i+1,j+1,k],ndarray[i+1,j+1,k+1],ndarray[i+1,j+1,k+2],
        ndarray[i+1,j+2,k],ndarray[i+1,j+2,k+1],ndarray[i+1,j+2,k+2],
        ndarray[i+2,j,k],ndarray[i+2,j,k+1],ndarray[i+2,j,k+2],
        ndarray[i+2,j+1,k],ndarray[i+2,j+1,k+1],ndarray[i+2,j+1,k+2],
        ndarray[i+2,j+2,k],ndarray[i+2,j+2,k+1],ndarray[i+2,j+2,k+2]])